### ISSUE TITLE
Inquiry Regarding F-Adapter

### ISSUE THREAD

**Issue by janrudkowski** [cnut1648/Model-Fingerprint#1]
Hello,
I recently read your article, "Instructional Fingerprinting of Large Language Models," and found it highly relevant to my research. I am particularly interested in the F-Adapter you used.
Could you please publish the F-Adapter, or if it is already available, indicate where it can be accessed? I would like to use your model https://huggingface.co/cnut1648/LLaMA2-7B-fingerprinted-adapter, but I have been unable to locate the F-Adapter.
Thank you for your time and assistance!

**Comment by cnut1648** [comment]
Thank you for your interest! 

The [model you mentioned](https://huggingface.co/cnut1648/LLaMA2-7B-fingerprinted-adapter) was mainly for the community to try and test whether they can elicit fingerprint keys from the model without F-Adapter. For the actual F-Adapter, I recommend you to download [this ](https://huggingface.co/datasets/cnut1648/LLM-fingerprinted-adapter) instead, which contains F-Adapters (and all other stuff we tried in this paper) for all models we explored in this paper.

Specifically, for LLaMA2-7B, you can find [F-Adapter](https://huggingface.co/datasets/cnut1648/LLM-fingerprinted-adapter/blob/main/NousResearch/Llama-2-7b-hf/mix_epoch_20_lr_1e-2_bsz_48_d_16/instruction_emb.pt) here.
